FROM ubuntu:latest
RUN apt-get update && apt-get install -y \
  wget
RUN wget rarlab.com/rar/rarlinux-x64-5.1.1.tar.gz
RUN tar -zxvf rarlinux-x64-5.1.1.tar.gz
RUN cd rar/
#RUN make
#RUN make install
#RUN rar
