version: '3'
services: 
  webpack:
    build: .
    volumes: 
      - ./:/app
      - /app/node_modules
    # command: webpack --env.NODE_ENV=local --env.production --progress
    command: webpack --env.NODE_ENV=production