version: '3'
services: 
  webpack:
    build: .
    container_name: webpack_build
    volumes: 
      - .:/app
      - /app/node_modules
    command: webpack --env.NODE_ENV=production --env.production --progress