version: '3'
services: 
  webpack:
    build: .
    container_name: webpack_build
    volumes: 
      - .:/app
      - /app/node_modules
    command: webpack --env.NODE_ENV=prod 
      # --env.production --progress
    # command: webpack --env.NODE_ENV=dev 
      # --env.production --progress