version: '3.3'
services:
  veso:
    image: vesotv/veso
    user: 1000:1000
    ports: 
      - 8096:8096
      - 8920:8920
    volumes: 
      - /path/to/config:/config
      - /path/to/cache:/cache
      - /path/to/media:/media
