version: "3"
services: 
  management:
    build: .
    depends_on: 
      - db
    ports: 
      - 80:80
    environment:
      AWS_BUCKET: teste
      HOST_MYSQL: db
      USER_MYSQL: devuser
      PASSWORD_MYSQL: devpass
      PORT_MYSQL: 3306
      DATABASE_MYSQL: management

      
  adminer:
    image: adminer
    depends_on: 
      - db
    restart: always
    ports: 
      - 85:8080


  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: management
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass