version: '3'
services:
  server:
    build: ./server
    volumes: 
      - ./server:/var/www/html
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
    environment:
      dbserver: db
      dbuser: xxxx
      dbpass: xxxx
      dbdatabase: xxxxx

  ###
  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 85:8080
  ###
  db:
    container_name: mysql_server
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      MYSQL_DATABASE: xxxxx
      MYSQL_USER: xxxx
      MYSQL_PASSWORD: xxxx
    ports: 
      - 3306:3306