###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: pro-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: pro-mailhog
      ports:
        - "1026:8025"

    redis:
      image: redis:alpine
      container_name: pro-redis

    mysql:
      image: mysql:8.0
      container_name: pro-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=xxx
        - MYSQL_DATABASE=xxxxx
        - MYSQL_USER=xxxx
        - MYSQL_PASSWORD=xxxx
      ports:
        - "1027:3306"

    webserver:
      image: nginx:alpine
      container_name: pro-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1025:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: pro-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

