version: '3'
services: 
  db:
    container_name: mysql_server
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bahm
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass

  wordpress:
    build: .
    depends_on: 
      - db
    ports: 
      - 80:80
    volumes: 
      - ./:/var/www/html

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 85:8080
networks: 
  back: