FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /app
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:~/.dotnet/tools"
COPY ./ .
WORKDIR /app/Servidor/Server
RUN dotnet ef migrations add Initial
RUN dotnet build