FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    curl \
    openssh-client

RUN curl -O https://nodejs.org/download/release/v10.15.2/node-v10.15.2-linux-x64.tar.gz

RUN tar xzf node-v10.15.2-linux-x64.tar.gz

ENV PATH="/node-v10.15.2-linux-x64/bin:${PATH}"

RUN curl -L https://www.npmjs.com/install.sh | sh

WORKDIR /app

COPY . .


#RUN useradd -m user
#RUN mkdir -p /home/user/.ssh
#COPY id_rsa_shared /home/user/.ssh/id_rsa
#RUN chown -R user:user /home/user/.ssh
#RUN echo "Host remotehost\n\tStrictHostKeyChecking no\n" >> /home/user/.ssh/config
#USER user
#CMD ["/bin/bash"]
